export const resourceKinds = Object.freeze([
  "wood",
  "stone",
  "scrap",
  "essence",
  "bossCore",
] as const);

export type ResourceKind = (typeof resourceKinds)[number];
export type CommonResourceKind = Exclude<ResourceKind, "bossCore">;
export const commonResourceKinds: readonly CommonResourceKind[] = Object.freeze(
  ["wood", "stone", "scrap", "essence"] as const,
);

export type ResourceBag = Record<ResourceKind, number>;
/** Immutable authored resource quantities such as costs, drops, and harvests. */
export type ReadonlyResourceBag = Readonly<ResourceBag>;

export interface Vector2 {
  readonly x: number;
  readonly y: number;
}

export type InputSource = "keyboard" | "tap-to-move" | "system";

export interface MoveCommand {
  readonly intent: Vector2;
  readonly source: InputSource;
  readonly at: number;
}

/** An explicit runtime-only destination issued by a primary canvas tap. */
export interface DestinationCommand {
  readonly destination: Vector2;
  readonly source: "tap-to-move";
  readonly at: number;
}

export const enemyKinds = Object.freeze([
  "scout",
  "brute",
  "spitter",
  "elite",
  "boss",
] as const);

export type EnemyKind = (typeof enemyKinds)[number];

export interface EnemyState {
  readonly id: string;
  readonly kind: EnemyKind;
  readonly position: Vector2;
  readonly hp: number;
  readonly maxHp: number;
  readonly damage: number;
  readonly dangerTier: number;
  readonly respawnAt: number | null;
  readonly defeated: boolean;
  /** Present only for the large boss generated by a timed encounter wave. */
  readonly isWaveBoss?: boolean;
  readonly bossName?: string;
}

/** A disposable visual/combat flight snapshot. It is never part of a save. */
export interface ProjectileState {
  readonly id: string;
  readonly origin: Vector2;
  readonly targetId: string;
  readonly targetPosition: Vector2;
  readonly progress: number;
  readonly style: AttackStyle;
  readonly homing?: boolean;
}

/** A short-lived close-range attack projection. It is never a projectile or save data. */
export interface CrescentAttackState {
  readonly id: string;
  readonly origin: Vector2;
  readonly direction: Vector2;
  readonly radius: number;
  readonly arcCosine: number;
  readonly progress: number;
}

/** A runtime-only resource bundle left by a completed lethal projectile impact. */
export interface FloorDropState {
  readonly id: string;
  readonly resource: ResourceKind;
  readonly amount: number;
  readonly position: Vector2;
}

/**
 * A collectible weapon relic left only by a defeated timed-wave boss. It is a
 * runtime projection, so an uncollected relic never enters a save document.
 */
export interface WeaponRelicDropState {
  readonly id: string;
  readonly position: Vector2;
  readonly waveIndex: number;
  readonly bossName: string;
}

export const buildingKinds = Object.freeze([
  "Campfire",
  "Workshop",
  "Farm",
  "Storage",
  "Healer",
] as const);

export type BuildingKind = (typeof buildingKinds)[number];

export interface BuildingState {
  readonly id: string;
  readonly kind: BuildingKind;
  readonly position: Vector2;
  readonly level: 1 | 2 | 3;
}

export const upgradeIds = Object.freeze([
  "sharpened-blade",
  "quick-hands",
  "iron-skin",
  "ember-aura",
  "long-reach",
  "chain-strike",
  "invigorating-edge",
  "trailblazer",
  "fortified-heart",
  "keen-focus",
] as const);

export type UpgradeId = (typeof upgradeIds)[number];

export const playerClasses = Object.freeze([
  "knight",
  "wizard",
  "archer",
] as const);

export type PlayerClass = (typeof playerClasses)[number];

export const playerStatKinds = Object.freeze([
  "strength",
  "dexterity",
  "agility",
  "luck",
  "vitality",
  "magic",
  "defense",
  "magicDefense",
] as const);

export type PlayerStatKind = (typeof playerStatKinds)[number];
export type PlayerStats = Readonly<Record<PlayerStatKind, number>>;

/**
 * The six player-controlled RO-inspired attributes. Defense values are
 * derived from Vitality and Magic and consequently are not allocatable.
 */
export const allocatablePlayerStatKinds = Object.freeze([
  "strength",
  "agility",
  "vitality",
  "magic",
  "dexterity",
  "luck",
] as const);

export type AllocatablePlayerStatKind =
  (typeof allocatablePlayerStatKinds)[number];

/** Persistent player choices, separate from class bases and derived stats. */
export type PlayerStatAllocations = Readonly<
  Record<AllocatablePlayerStatKind, number>
>;

export const emptyPlayerStatAllocations = (): PlayerStatAllocations => ({
  strength: 0,
  agility: 0,
  vitality: 0,
  magic: 0,
  dexterity: 0,
  luck: 0,
});

export const emptyPlayerStats = (): PlayerStats => ({
  strength: 0,
  dexterity: 0,
  agility: 0,
  luck: 0,
  vitality: 0,
  magic: 0,
  defense: 0,
  magicDefense: 0,
});

/** Current progression levels. Historical save validators keep their own L5 cap. */
export const playerLevels = Object.freeze([
  0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
  22, 23, 24, 25,
] as const);

export type PlayerLevel = (typeof playerLevels)[number];

/** IDs shipped in the historical L5 catalogue. Keep append-only. */
export const legacyClassSkillIds = Object.freeze([
  "knight-iron-guard",
  "knight-wide-slash",
  "knight-heavy-blade",
  "knight-rapid-cuts",
  "knight-execution-arc",
  "knight-crescent-sweep",
  "knight-bulwark",
  "knight-whirlwind",
  "wizard-flame-orb",
  "wizard-wide-blast",
  "wizard-arcane-haste",
  "wizard-mana-siphon",
  "wizard-nova",
  "wizard-aether-ward",
  "wizard-meteor",
  "wizard-spellweave",
  "archer-longbow",
  "archer-barbed-arrow",
  "archer-quickdraw",
  "archer-volley",
  "archer-piercing-arrow",
  "archer-trailstep",
  "archer-eagle-eye",
  "archer-multishot",
] as const);

export type LegacyClassSkillId = (typeof legacyClassSkillIds)[number];

export const classSkillRoutes = Object.freeze(["boss", "aoe"] as const);
export type ClassSkillRoute = (typeof classSkillRoutes)[number];

export const classSkillTiers = Object.freeze([
  1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
  23, 24,
] as const);
export type ClassSkillTier = (typeof classSkillTiers)[number];
export type ExtendedClassSkillTier = Exclude<ClassSkillTier, 1 | 2 | 3 | 4>;
export const maximumClassSkillTier = 24 as const;

export type ExtendedClassSkillId =
  `${PlayerClass}-${ClassSkillRoute}-${ExtendedClassSkillTier}`;
export type ClassSkillId = LegacyClassSkillId | ExtendedClassSkillId;

const extendedClassSkillIds: readonly ExtendedClassSkillId[] = Object.freeze(
  playerClasses.flatMap((playerClass) =>
    classSkillRoutes.flatMap((route) =>
      Array.from(
        { length: maximumClassSkillTier - 4 },
        (_, index) =>
          `${playerClass}-${route}-${index + 5}` as ExtendedClassSkillId,
      ),
    ),
  ),
);

/** Current runtime catalogue; V2/V3 validation deliberately uses legacyClassSkillIds. */
export const classSkillIds: readonly ClassSkillId[] = Object.freeze([
  ...legacyClassSkillIds,
  ...extendedClassSkillIds,
]);

export type AttackStyle = "basic" | "slash" | "magic" | "arrow";

export interface ClassProgression {
  readonly experience: number;
  readonly level: PlayerLevel;
  readonly playerClass: PlayerClass | null;
  readonly skillIds: readonly ClassSkillId[];
  /** Normalized persistent player allocations; class bases never enter here. */
  readonly allocatedStats: PlayerStatAllocations;
  /**
   * Current class weapon rank. Released progression extensions may omit this
   * field; hydration normalizes missing historical values to zero.
   */
  readonly weaponRank?: number;
}

export interface PlayerState {
  readonly position: Vector2;
  readonly hp: number;
  readonly maxHp: number;
}

export interface WorldIdentity {
  readonly seed: string;
  readonly generatorVersion: string;
}

export interface ChunkObstacle {
  readonly id: string;
  readonly position: Vector2;
}

export interface ChunkCampfire {
  readonly id: string;
  readonly position: Vector2;
  readonly kind: "home" | "wild";
}

export interface DangerProfile {
  readonly tier: number;
  readonly label: string;
  readonly distance: number;
  readonly healthMultiplier: number;
  readonly damageMultiplier: number;
  readonly dropMultiplier: number;
}

export interface ChunkSpawn {
  readonly id: string;
  readonly kind: EnemyKind;
  readonly position: Vector2;
  readonly danger: DangerProfile;
}

export interface ChunkRecipe {
  readonly coordinate: Vector2;
  readonly key: string;
  readonly domainSeeds: Readonly<Record<string, number>>;
  readonly obstacles: readonly ChunkObstacle[];
  readonly campfires: readonly ChunkCampfire[];
  readonly spawns: readonly ChunkSpawn[];
}

export interface CombatStats {
  readonly attackDamage: number;
  readonly attackIntervalSeconds: number;
  readonly attackRange: number;
  readonly moveSpeed: number;
  readonly chainTargets: number;
  readonly attackStyle: AttackStyle;
  readonly classSecondaryDamageMultiplier: number;
  readonly classAreaRadius: number;
  readonly classArcCosine: number;
  readonly weaponProjectileCount: number;
  readonly weaponProjectileDamageMultiplier: number;
  readonly weaponProjectileHoming: boolean;
  /** RO-inspired derived mitigation and deterministic chance values. */
  readonly physicalDefense: number;
  readonly magicDefense: number;
  readonly dodgeChance: number;
  readonly physicalCriticalChance: number;
  readonly physicalCriticalDamageMultiplier: number;
}

/**
 * Current in-memory state used to hydrate a GameSession. The frozen released
 * schema-2 wire DTO lives independently in persistence/saveV2.ts.
 */
export interface CurrentSave {
  readonly schemaVersion: 4;
  readonly world: WorldIdentity;
  readonly player: PlayerState;
  readonly resources: ResourceBag;
  readonly buildings: readonly BuildingState[];
  readonly defeatedBossIds: readonly string[];
  readonly upgrades: readonly UpgradeId[];
  readonly nextBuildingSerial: number;
  readonly committedAt: number;
  readonly savePointId: string;
  readonly savePointPosition: Vector2;
  /** V4 explicitly persists normalized progression and player allocations. */
  readonly classProgression: ClassProgression;
}

/** Compatibility alias for callers that still use the historical name. */
export type SaveDocument = CurrentSave;

export interface ValidCampfireSaveRequest {
  readonly document: CurrentSave;
  readonly savePointLabel: string;
}

export const emptyResources = (): ResourceBag => ({
  wood: 0,
  stone: 0,
  scrap: 0,
  essence: 0,
  bossCore: 0,
});
